import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Nav from '@/components/element/Nav'

import { WindowSizeProvider } from "../context/WindowSizeContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='lg:flex lg:gap-[36px] md:p-[25px] lg:p-[32px] max-w-[100vw] h-[100vh] bg-dark_blue'>
          <WindowSizeProvider>
            <Nav />
            {children}
          </WindowSizeProvider>
        </div>
      </body>
    </html>
  )
}
